### ISSUE TITLE
FMAlign2 parallel issue

### ISSUE THREAD

**Issue by m-fayer** [metaphysicser/FMAlign2#2]
Hi,

I installed FMAlign2 on our old CentOS 7 machine following the instructions [here](https://github.com/malabz/FMAlign2):

> git clone https://github.com/metaphysicser/FMAlign2.git
> cd FMAlign2
> make M64=1

The installation looks ok. But when I ran the program by command `FMAlign2 -i test.fa -t 4 -o out.fa`, an error occurred: `Error: Fail to align in parallel!` The error persisted even when I set the option `-t 1`.

I tried commands `chmod -R 777 FMAlign2/` and `FMAlign2/ext/mafft/linux/usr/libexec/mafft/disttbfast -i test.fa > out.fa` and they looked fine.

Any suggestion is highly appreciated. The full screen output is:

> \#############################################################
> \#               FMAlign2 algorithm info                     #
> \#-----------------------------------------------------------#
> \# Mode: 64 bit                                              #
> \# Thread: 1                                                 #
> \# Minimum MEM length: square root of mean length            #
> \# Sequence coverage: -1                                     #
> \# Parallel align method: mafft                              #
> \#############################################################
> \#                   Reading Data...                         #
> \#-----------------------------------------------------------#
> \# test.fa could be accessed #
> \# Data Memory Usage: 0.03 GB                                #
> \# Sequence Number: 6                                        #
> \#-----------------------------------------------------------#
> \#                    Finding MEM...                         #
> \#-----------------------------------------------------------#
> \# Minimal MEM length is set to 30                           #
> \# Filter mode is set to local                               #
> \# Minimal sequence coverage is set to 1.000000              #
> \# Suffix construction time: 8.02 seconds                    #
> \# Minimal cross sequence number: 6                          #
> \# Sequence divide parts: 3                                  #
> \# MEM process time: 0.202 seconds.                          #
> \#-----------------------------------------------------------#
> \#                Parallel Aligning...                       #
> \#-----------------------------------------------------------#
> \# SW expand time: 0.04 seconds.                             #
> \# Warning: Starts calling FMAlign2 recursively to align ./temp/task-0_qjjdkfutjw.fasta#
> **Error**: Fail to align in parallel!

**Comment by metaphysicser** [comment]
Please make sure that your FMAlign2 is run under path/to/FMAlign2. I apologize for this user-unfriendly aspect, but FMAlign2 can only correctly locate the path to mafft when run in that directory. I’m sorry for the inconvenience this has caused you.

Recently, many users have reported this issue. After I finish my current tasks, I will configure FMAlign2 to use conda instead of the original source installation.

**Comment by m-fayer** [comment]
Thanks! The command looks working now.
