### ISSUE TITLE
How int input multiple fasta files

### ISSUE THREAD

**Issue by Xiaojun928** [metaphysicser/FMAlign2#3]
Hi,

Thanks for contributing to this fascinating tool.
According to your example, only one Fasta file was given as input. How can I provide multiple Fasta files for FMAlign2?
Please note that all my samples are assembled as draft genomes, so each has more than two contigs. Thanks in advance.

Best,
Xiaojun

**Comment by metaphysicser** [comment]
Hello, FMAlign2 is suitable for aligning multiple fully assembled genomes. If your data consists of many contigs, and these contigs are fragmented with little overlap between them, FMAlign2 may not be the best choice for your data.

If you still want to run it, you can try concatenating the multiple Fasta files into one using the command “cat file1.fasta file2.fasta file3.fasta > combined.fasta” and then attempt the alignment. However, I anticipate that the results may not be very good.

**Comment by Xiaojun928** [comment]
Thanks for your quick response! I may try other tools for my draft genomes. Thank you!
